### ISSUE TITLE
Impossible to generate a customization without login in a Springboot project

### ISSUE THREAD

**Issue by ShihTAN** [Mobioos/Mobioos-Forge#4] opened 2023-01-12 09:21 UTC
Describe the bug
Impossible to generate a variant with a SpringBoot project without login. We observe the folder of this variant appears then disappears in the folder "~/mobioos-forge-customizations".

Reproduce
Steps to reproduce the behavior :

1. Open the project I sent
2. Generate a variant by MF: create a customizations
3. Select all features except the feature login
4. Save and generate (observe at the same time the folder " ~/mobioos-forge-customizations " )

Desktop (please fill in the following information) :

Operating system: Linux version 5.15.0-57-generic (Ubuntu 20.04.1)
Mobioos Forge version: 2.1.2
VS code version: 1.74.2

**Comment by KarimGhallab** [comment] 2023-01-12 10:03
Thanks for the feedback, the issue is usually due to a wrong file mapping while mapping the features into the source code.
However, MF should prevent such file-mappings to occure.
A fix will be published in the next release of MF!

**Comment by KarimGhallab** [comment] 2023-03-06 08:08
Fixed with version 2.1.3 of Mobioos Forge.

**Closed by KarimGhallab** 2023-03-06 08:08 UTC
Labels: bug
